# Generated by Django 5.2.5 on 2025-08-18 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Userr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=128)),
                ('PhoneNumber', models.IntegerField(blank=True, null=True)),
                ('YearsOfExperience', models.IntegerField(blank=True, null=True)),
                ('Location', models.CharField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='UserImg')),
                ('IsNotifications', models.BooleanField(default=True)),
                ('IsServices', models.BooleanField(default=True)),
                ('TypeOfService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.services')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(blank=True, null=True)),
                ('HourlyPrice', models.IntegerField()),
                ('IdClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to='MyApp.userr')),
                ('IdUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to='MyApp.userr')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=500)),
                ('Isrequest', models.BooleanField(default=False)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.userr')),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Evaluation', models.FloatField()),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.userr')),
            ],
        ),
    ]
