# Generated by Django 5.2.5 on 2025-08-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_servicerequest_clientorderstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='UserOrderStatus',
        ),
    ]
