# Generated by Django 5.2.5 on 2025-09-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_emailcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userr',
            name='PhoneNumber',
            field=models.CharField(blank=True, null=True),
        ),
    ]
