# Generated by Django 5.2.5 on 2025-09-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_alter_userr_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='ClientOrderStatus',
            field=models.IntegerField(default=0),
        ),
    ]
