# Generated by Django 5.2.5 on 2025-09-03 21:29

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_alter_servicerequest_clientorderstatus'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userr',
            index=django.contrib.postgres.indexes.HashIndex(fields=['FullName'], name='full_name_hash_idx'),
        ),
    ]
