# Generated by Django 5.2.5 on 2025-09-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_userr_full_name_hash_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userr',
            name='full_name_hash_idx',
        ),
        migrations.AddIndex(
            model_name='userr',
            index=models.Index(fields=['FullName'], name='full_name_idx'),
        ),
    ]
