# Generated by Django 5.2.5 on 2025-09-03 21:40

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_remove_userr_full_name_hash_idx_userr_full_name_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userr',
            name='full_name_idx',
        ),
        migrations.AddIndex(
            model_name='userr',
            index=django.contrib.postgres.indexes.GinIndex(fields=['FullName'], name='full_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
