# Generated by Django 5.2.5 on 2025-09-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_remove_userr_full_name_idx_userr_full_name_trgm_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userr',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
