# Generated by Django 5.2.5 on 2025-09-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_alter_userr_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userr',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Img/'),
        ),
    ]
