# Generated by Django 5.2.5 on 2025-09-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_alter_userr_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userr',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
