# Generated by Django 5.2.5 on 2025-09-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_alter_userr_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userr',
            name='img',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/divtg1bzt/image/upload/v1757035773/userImg_catnzo.jpg', null=True),
        ),
    ]
