# Generated by Django 5.2.5 on 2025-09-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_alter_userr_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='Isrequest',
            field=models.IntegerField(),
        ),
    ]
